# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Game.create(
  [
    {
      title: "Takenoko",
      designer: "Antoine Bauza",
      artist: "Nicolas Fructus, Picksel, Yuio",
      publisher: "Asmodee",
      min_players: 2,
      max_players: 4,
      play_time: 45,
      year: 2011,
    },
    {
      title: "Rising Sun",
      designer: "Eric M. Lang",
      artist: "Edgar Skomorowski, Adrian Smith",
      publisher: "CMON",
      min_players: 2,
      max_players: 6,
      play_time: 120,
      year: 2018,
    },
    {
      title: "Coimbra",
      designer: "Eric M. Lang",
      artist: "Chris Quilliams",
      publisher: "Eggertspiele",
      min_players: 2,
      max_players: 4,
      play_time: 90,
      year: 2018,
    },
    {
      title: "Blood Rage",
      designer: "Eric M. Lang",
      artist: "Adrian Smith",
      publisher: "CMON",
      min_players: 3,
      max_players: 5,
      play_time: 120,
      year: 2015,
    },
    {
      title: "Ticket to Ride",
      designer: "Alan R. Moon",
      artist: "Cyrille Daujean, Julien Delval",
      publisher: "Days of Wonder",
      min_players: 2,
      max_players: 5,
      play_time: 60,
      year: 2004,
    },
    {
      title: "HATE",
      designer: "Eric M. Lang",
      artist: "Adrian Smith",
      publisher: "CMON",
      min_players: 2,
      max_players: 2,
      play_time: 120,
      year: 2019,
    },
    {
      title: "Sleeping Gods",
      designer: "Ryan Laukat",
      artist: "Ryan Laukat",
      publisher: "Red Raven Games",
      min_players: 1,
      max_players: 4,
      play_time: 120,
      year: 2020,
    },
    {
      title: "Tapestry",
      designer: "Jaime Stegmaier",
      artist: "Andrew Bosley, Rom Brown",
      publisher: "Stonemaier Games",
      min_players: 1,
      max_players: 5,
      play_time: 120,
      year: 2019,
    },
    {
      title: "The Ancient World",
      designer: "Ryan Laukat",
      artist: "Ryan Laukat",
      publisher: "Red Raven Games",
      min_players: 2,
      max_players: 4,
      play_time: 90,
      year: 2019,
    },
    {
      title: "Cottage Garden",
      designer: "Uve Rosengerg",
      artist: "Andrea Boekhoff",
      publisher: "Stronghold Games",
      min_players: 1,
      max_players: 4,
      play_time: 60,
      year: 2016,
    },
    {
      title: "Dale of Merchants",
      designer: "Sami Laakso",
      artist: "Sami Laakso",
      publisher: "Devir",
      min_players: 2,
      max_players: 4,
      play_time: 30,
      year: 2015,
    },
  ]
)
